version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=todouser
      - MARIADB_DATABASE=todos
      - MARIADB_PASSWORD=Password1

  todoApp:
    tty: true
    image: docker.io/bitnami/laravel:8
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=todouser
      - DB_DATABASE=todos
      - DB_PASSWORD=Password1
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows